name: "Deploy Notlify Action"
description: "Deploy the website"
inputs:
  applicationName:
    description: "The name of the application"
    required: true
  distributionDirectory:
    description: "The location of the built assets"
    required: true
  apiKey:
    description: "The api key to the application"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
